@extends('web.layouts.app')
@section('title', 'User Agreement')
@section('styles')

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">
<style type="text/css">

#over img {
  margin-left: auto;
  margin-right: auto;
  display: block;
}
</style>
@endsection

@section('content')
<section class="page__img" style="background-image: url('{{ asset('web/img/apply_bg.jpg') }}')">
    <div class="container">
        <div class="row">
            <div class="title__wrapp">
                {{-- <div class="page__subtitle title__grey">Looking for talent ?</div> --}}
                <h1 class="page__title">User Agreement</h1>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="section how-it-works">
        <div class="container">
			<div class="row">
				<div class="col-md-offset-2 col-md-8" style="text-align: justify;">
					<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>This User Agreement (&quot;Agreement&quot;) is an agreement between you, an individual or an individual acting on behalf a minor, a corporation, partnership, or other legal entity that will be using The Talent Depot services (&quot;User&quot;). &nbsp;The Talent Depot is a North Carolina LLC, located in Charlotte, North Carolina.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>1. ACKNOWLEDGMENT AND ACCEPTANCE OF AGREEMENT</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;The Services, provided by the Company, are provided to User under the terms and conditions of this Agreement and supersedes any prior agreements pertaining to the subject matter contained herein.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>2. DESCRIPTION OF SERVICES</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;The Company is an online service, which provides talented individuals the capability to create, edit and present their personal URL and online portfolio to an unlimited number of individuals, businesses, service providers, such as Talent Agents, Talent Managers, Casting Directors, Photographers, Producers, Advertising Agencies and the like, who utilize our website to find talent for their paid and unpaid projects. Additionally, when logged in, Standard and Professional members only send their personal, unique URL, which links to their online portfolio, individuals, businesses, service providers, using the electronic mail (&ldquo;e-mail&rdquo;) feature within their profile.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>3. MEMBERSHIP ELIGIBILITY</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;All individuals, regardless of race, gender, or ethnicity are eligible. Individuals under the age of 18 may register with parental consent. Therefore, we acknowledge that Users under the age 18 have received parental consent.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>4. USER&rsquo;S REGISTRATION OBLIGATIONS</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;In consideration of use of the Services, User agrees to: (a) provide true, accurate, current, and complete information about User as prompted on the various web pages within the User&apos;s portfolio; and (b) to maintain and update this information in a timely manner and thereafter keep it true, accurate, current, and complete. User agrees to allow Company the unlimited use of User&rsquo;s profile, free of charge, in Company marketing and advertisements. If any information provided by User (&quot;Profile Data&quot;) is untrue, inaccurate, not current, or incomplete, Company has the right to terminate User&apos;s account and refuse any and all current and/or future use of the Services.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>5. USER NAME, MEMBER ACCOUNT, PASSWORD AND SECURITY</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;For the protection of our members we do not allow personal contact information (phone numbers, physical addresses or personal e-mail addresses) to be seen online. Therefore, Users may only be contacted indirectly through their cell phone number (voice or sms) and e-mail. User&rsquo;s email address will be used as their username, so long as it is not obscene, unlawful, or otherwise objectionable, in Company&apos;s sole discretion. User will provide a password, which will allow access to be Company web site. User is responsible for maintaining the confidentiality of the password and account, and is fully responsible for all activities that occur under User&apos;s account. User agrees to immediately notify Company of any unauthorized use of User&apos;s password or account or of any other breach of security.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>6. UPLOADING DATA</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;By the submission or uploading of any data or media (including any images, audio files or video media) to the Company you warrant that (a) you are the owner of such data and media, or have been granted the rights necessary from the owner of such data or media to the Company, and (b) the use of such data or media by the Company will not infringe the intellectual property rights of, or otherwise violate the rights of any third party.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>7. INTERNATIONAL USE</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;Recognizing the global nature of the Internet, you agree to comply with all applicable local rules including but not limited to rules regarding online conduct and acceptable content. The Company makes no representation that materials on this site are appropriate or available for use in locations outside the United States, and accessing them from territories where their contents are illegal is prohibited. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>8. FEES, ANNUAL RENEWAL, CHARGEBACK AND CANCELLATION</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br> If offered a trial account, the User has seven (7) day following the initial registration to become a paying membership. If after the 8<sup>th</sup> day, the trial member does not become a paying member, their trial account may be terminated without notice.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>To remain in good standing, members will automatically be charged the annual renewal fee on the payment account, bank, credit card, etc. used at the time of the member&rsquo;s join date. &nbsp;If a renewal payment is declined, the User&rsquo;s membership will be suspended until the User contacts The Talent Depot and makes payment via phone. &nbsp;The Company has a no refund policy. &nbsp;In the event a cancellation or a termination due to the failure to adhere to requirements detailed in this User Agreement, no refund will be made, however, at the discretion of the Company, the member&rsquo;s profile will remain on active status until the following anniversary date, unless requested otherwise. The Talent Depot reserves the right to change this policy at any time without prior notice. Members may cancel at any time. To cancel, email&nbsp;</span><a href="mailto:support@thetalentdepot.com"><strong><span style='font-size:19px;font-family:"Arial",sans-serif;'>support@thetalentdepot.com</span></strong></a><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>. &nbsp;</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>9. ONLINE WORKSHOPS</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;Online workshops may be prerecorded videos or live presentations. &nbsp;There is no refund policy. A free introduction video is available for review prior to purchasing any online workshops. After reviewing the introduction video, talent have the option to sign-up for workshops by registering and paying the advertised fee.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>10. USER CONDUCT</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;User agrees to abide by all applicable local, state, national, and international laws and regulations during use of the Services. User agrees to be solely responsible for the contents of User&apos;s private and public communications, whether uploaded, posted, emailed, or otherwise transmitted through the Services. User agrees: (1) not to use the Services for illegal purposes; (2) User agrees not to upload, post, email, or otherwise transmit through the Services: (a) any unlawful, harassing, libelous, privacy invading, abusive, threatening, harmful, vulgar, obscene, indecent, tortuous, or otherwise objectionable material of any kind; (b) any material that violates the rights of another, including, but not limited to, the intellectual property rights of another; (c) any material that violates any applicable local, state, national, or international law or regulation; or (d) unsolicited or unauthorized advertisements, promotional materials, &quot;junk mail,&quot; &quot;spam,&quot; &quot;chain letters,&quot; or other forms of solicitation. User acknowledges and agrees that Company may ban User from future use of the Services if User does not comply with Company&apos;s standards of conduct, even if User attempts to use the Services through another Client or under a different name. Furthermore, User acknowledges and agrees that Company may recover damages from User if User violates these terms.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>11. MONITORING AND ENFORCEMENT</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;While we have the right to monitor activity and content associated with the Company Service, we are not obligated to do so. And since we do not, and may not have the ability to, control or actively monitor content we don&rsquo;t guarantee its accuracy, integrity or quality. Because community standards vary and individuals sometimes choose not to comply with our policies and practices, in the process of using our website, you may be exposed to content that you find offensive or objectionable. You can contact us by email at&nbsp;</span><a href="mailto:support@thetalentdepot."><span style='font-size:19px;font-family:"Arial",sans-serif;'>support@thetalentdepot.</span></a><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>com to let us know of content that you find objectionable. We may investigate the complaints and violations of our policies that come to our attention and may take any action that we believe is appropriate, including, but not limited to issuing warnings, removing the content, suspending, or terminating a membership. However, because situations and interpretations vary, we also reserve the right not to take any action. Under no circumstances will we be liable in any way for any content, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of, access to, or denial of access to any content on the website.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>12. TERMINATION</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;(a) User agrees that Company, Client, or their third party service providers may terminate User&apos;s password, account, or use of the Services if Company, Client, or their third party service providers believe: (i) that User has violated or acted inconsistently with the letter or spirit of this Agreement; (ii) that User has violated the rights of Company, Client, or their third party service providers or other Users or parties. User agrees Company and Client may immediately delete User&apos;s account and all related information, communications, and files, and may bar any further access to such account, communications, files, or the Services under any provision of this Agreement. User also acknowledges and agrees that termination of any of the Services may be affected without prior notice.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>13. INDEMNITY</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;By accepting this User Agreement, you agree to indemnify and otherwise hold harmless the Company, its officers, employees, agents, subsidiaries, and affiliates from any direct, indirect, incidental, special, consequential, or exemplary damages resulting from i) your use of the Company Service; ii) unauthorized access to or alteration of your online portfolio with or through the Company Service, or iii) any other matter relating to the Company Service. Any business transactions which may arise between Users from their use of Company are the sole responsibility of the Users involved. Without limitation of the terms and conditions set forth in our Privacy Policy, you understand and agree that the Company may disclose personally identifiable information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to comply with legal process, enforce this User Agreement, or protect the rights, property, or safety of Company, its Users, and the public.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>14. COMPANY&apos;S PROPRIETARY RIGHTS</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;User acknowledges and agrees that this website may contain proprietary and confidential information that is protected by applicable intellectual property and other laws. User further acknowledges and agrees that Content contained in or information presented to you through this online service is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by The Talent Depot services, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Website, in whole or in part.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>15. DISCLAIMER OF WARRANTIES</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;YOU UNDERSTAND AND AGREE THAT THE COMPANY SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS AND THAT THE COMPANY DOES NOT ASSUME ANY RESPONSIBILITY FOR PROMPT OR PROPER DELIVERY, OR RETENTION OF ANY USER INFORMATION OR COMMUNICATIONS BETWEEN USERS. COMPANY ASSUMES NO RESPONSIBILITY FOR THE ACCURACY OR EXISTENCE OF ANY COMMUNICATIONS BETWEEN USERS. COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. COMPANY MAKES NO WARRANTY THAT (i) THE COMPANY SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE COMPANY SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE COMPANY SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL OBTAINED BY YOU THROUGH THE COMPANY SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM COMPANY OR THROUGH OR FROM THE COMPANY SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS USER AGREEMENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>16. ENTIRE AGREEMENT</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;The User Agreement constitutes the entire agreement between you and Company and governs your use of the Company Service, superseding any prior agreements between you and the Company.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>17. LIMITATION OF LIABILITY</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;YOU EXPRESSLY UNDERSTAND AND AGREE THAT COMPANY SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES). SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN NO EVENT WILL THE COMPANY TOTAL CUMULATIVE DAMAGES EXCEED USD $100.</span></p>
                    <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'>18. GOVERNING LAW</span></strong><span style='font-size:19px;font-family:"Arial",sans-serif;color:gray;'><br>&nbsp;The User Agreement between you and the Company will be governed by and construed in accordance with the laws of the State of North Carolina without regard to conflict of laws principles.</span></p>
				</div>
			</div>
        </div>
    </div>
</section>

@endsection